use dwyzdb;

CREATE TABLE IF NOT EXISTS `b_privilege` (
  `PRIVILEGE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRIVILEGE_NAME` varchar(255) DEFAULT NULL,
  `URL` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`PRIVILEGE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `b_role` (
  `ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=18 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `b_user` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `ENABLE` tinyint(255) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `food` (
  `FOOD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FOOD_SELLER_ID` int(11) DEFAULT NULL COMMENT 'FOREIGN KEY',
  `FOOD_TYPE_ID` int(11) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  `UNIT_PRICE` double DEFAULT NULL,
  PRIMARY KEY (`FOOD_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `food_menu` (
  `FOOD_MENU_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FOOD_SELLER_ID` int(11) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`FOOD_MENU_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `food_seller` (
  `FOOD_SELLER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `PHONE` varchar(512) DEFAULT NULL,
  `BUSINESS_HOURS` varchar(255) DEFAULT NULL COMMENT '营业时间',
  `DELIVERY_AREA` varchar(255) DEFAULT NULL,
  `DELIVERY_PRICE_MIN` decimal(10,2) DEFAULT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `NOTE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`FOOD_SELLER_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=35 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `food_seller_type` (
  `FOOD_SELLER_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `ICON` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`FOOD_SELLER_TYPE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `food_type` (
  `FOOD_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`FOOD_TYPE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `location_area` (
  `LOCATION_AREA_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'pk',
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`LOCATION_AREA_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `location_business` (
  `LOCATION_BUSINESS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `DESCRIPTION` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`LOCATION_BUSINESS_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `order_form` (
  `ORDER_FORM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FOOD_SELLER_ID` int(11) DEFAULT NULL,
  `DEFINE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ORDER_FORM_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `rel_area_business` (
  `REL_AREA_BUSINESS_ID` int(11) NOT NULL,
  `LOCATION_AREA_ID` int(11) DEFAULT NULL,
  `LOCATION_BUSINESS_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`REL_AREA_BUSINESS_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `rel_area_seller` (
  `REL_AREA_SELLER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOCATION_AREA_ID` int(11) DEFAULT NULL,
  `FOOD_SELLER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`REL_AREA_SELLER_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=33 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `rel_business_seller` (
  `REL_BUSINESS_SELLER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOCATION_BUSINESS_ID` int(11) DEFAULT NULL,
  `FOOD_SELLER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`REL_BUSINESS_SELLER_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=38 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `rel_food_seller_type` (
  `REL_FOOD_SELLER_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FOOD_SELLER_ID` int(11) DEFAULT NULL,
  `FOOD_SELLER_TYPE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`REL_FOOD_SELLER_TYPE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `rel_privilege_role` (
  `REL_PRIVILEGE_ROLE_ID` int(255) NOT NULL AUTO_INCREMENT,
  `PRIVILEGE_ID` int(11) DEFAULT NULL,
  `ROLE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`REL_PRIVILEGE_ROLE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `rel_user_role` (
  `REL_USER_ROLE_ID` int(255) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) DEFAULT NULL,
  `ROLE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`REL_USER_ROLE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `r_order_form_food` (
  `ORDER_FORM_FOOD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ORDER_FORM_ID` int(11) DEFAULT NULL,
  `FOOD_ID` int(11) DEFAULT NULL,
  `AMOUNT` int(11) DEFAULT NULL,
  PRIMARY KEY (`ORDER_FORM_FOOD_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `b_recommend` (
  `RECOMMEND_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) NOT NULL,
  `CONTENT` varchar(1024) NOT NULL,
  PRIMARY KEY (`RECOMMEND_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;













